/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadias;

import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author endfox
 */
public class Ventanaempresa extends javax.swing.JFrame {
        ObjectContainer dbempresa;
        Menu menu;
    /**
     * Creates new form Ventanaempresa
     * @param menu
     * @param dbempresa
     */
        
    public Ventanaempresa(Menu menu,ObjectContainer dbempresa) {
        this.menu = menu;
        this.dbempresa = dbempresa;
        initComponents();
        this.setMarginJText();
        this.actualizarLista();
        
    }
    
    private void setMarginJText(){
        this.jTNombre.setBorder(BorderFactory.createCompoundBorder(
            this.jTNombre.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        this.jTDireccion.setBorder(BorderFactory.createCompoundBorder(
            this.jTDireccion.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
    }
    
    private void insertarDatos(String nombre, String direccion){
        if(nombre.isEmpty() || direccion.isEmpty()){
            this.jLStatus.setForeground(Color.RED);
            this.jLStatus.setText("Alguno de los campos esta vacio");
        }
        else{
            Empresa em = new Empresa(nombre,direccion);
            this.dbempresa.store(em);
            this.jLStatus.setForeground(Color.BLUE);
            this.jLStatus.setText("Empresa ingresada correctamente");
        }
    }
    
    private void actualizarLista(){
        Empresa em = null;
        this.jCEmpresas.removeAllItems();
        ObjectSet resultado = this.dbempresa.queryByExample(em);
	while(resultado.hasNext()){
           Empresa empl = (Empresa) resultado.next();
           this.jCEmpresas.addItem(empl.getNombre());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jLStatus = new javax.swing.JLabel();
        jBInsertar = new javax.swing.JButton();
        jTDireccion = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jLEmpresa = new javax.swing.JLabel();
        jCEmpresas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(40, 49, 67));
        jPanel2.setMaximumSize(new java.awt.Dimension(452, 300));

        jPanel1.setBackground(new java.awt.Color(239, 240, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLTitulo.setText("Añade los datos de una empresa");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jBRegresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menor-que-48.png"))); // NOI18N
        jBRegresar.setBorder(null);
        jBRegresar.setBorderPainted(false);
        jBRegresar.setContentAreaFilled(false);
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        jLStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLStatus.setForeground(new java.awt.Color(153, 102, 0));
        jPanel1.add(jLStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 280, 20));

        jBInsertar.setBackground(new java.awt.Color(239, 240, 242));
        jBInsertar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBInsertar.setText("Añadir empresa");
        jBInsertar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 17, 78), 2));
        jBInsertar.setBorderPainted(false);
        jBInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertarActionPerformed(evt);
            }
        });

        jTDireccion.setBackground(new java.awt.Color(239, 240, 242));
        jTDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTDireccion.setBorder(null);

        jTNombre.setBackground(new java.awt.Color(239, 240, 242));
        jTNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTNombre.setBorder(null);

        jLNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(239, 240, 242));
        jLNombre.setText("Nombre:");

        jLDireccion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(239, 240, 242));
        jLDireccion.setText("Dirección:");

        jLEmpresa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLEmpresa.setForeground(new java.awt.Color(239, 240, 242));
        jLEmpresa.setText("Ver empresas");

        jCEmpresas.setBackground(new java.awt.Color(239, 240, 242));
        jCEmpresas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNombre)
                    .addComponent(jLDireccion))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jCEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLEmpresa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jBInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDireccion))
                .addGap(18, 18, 18)
                .addComponent(jBInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLEmpresa)
                .addGap(18, 18, 18)
                .addComponent(jCEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertarActionPerformed
        // TODO add your handling code here:
        String nombre = this.jTNombre.getText();
        String direccion = this.jTDireccion.getText();
        this.jTNombre.setText("");
        this.jTDireccion.setText("");
        this.insertarDatos(nombre, direccion);
        this.actualizarLista();
    }//GEN-LAST:event_jBInsertarActionPerformed

    private void jCEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEmpresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEmpresasActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        this.setVisible(false);
        this.menu.setVisible(true);
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaempresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInsertar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JComboBox<String> jCEmpresas;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
