/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadias;

import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.ext.DatabaseClosedException;
import com.db4o.ext.Db4oIOException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author endfox
 */
public class VentanaAlumnos extends javax.swing.JFrame {
    ObjectContainer dbempresa;
    ObjectContainer dbalumno;
    Menu menu;
    ArrayList <String> carreras;
    ArrayList <String> especialidadestic;
    /**
     * Creates new form VentanaAlumnos
     * @param menu
     * @param dbempresa
     * @param dbalumno
     */
    public VentanaAlumnos(Menu menu, ObjectContainer dbempresa,ObjectContainer dbalumno) {
        this.menu=menu;
        this.dbempresa=dbempresa;
        this.dbalumno=dbalumno;
        
        this.carreras = new ArrayList<>();
        this.especialidadestic = new ArrayList<>();
        this.carreras.add("TIC");
        this.carreras.add("GST");
        this.especialidadestic.add("Sistemas");
        this.especialidadestic.add("Diseño gráfico");
        initComponents();
        this.fillCarreras();
        this.setPaddingJText();
        this.fillEmpresas();
        
        
    }
    
    private void setPaddingJText(){
        this.jTNombre.setBorder(BorderFactory.createCompoundBorder(
            this.jTNombre.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        this.jTApellidos.setBorder(BorderFactory.createCompoundBorder(
            this.jTApellidos.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        this.jTMatricula.setBorder(BorderFactory.createCompoundBorder(
            this.jTMatricula.getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
    }
    
    private void fillEmpresas(){
        Empresa emp = null;
        ObjectSet resultado = this.dbempresa.queryByExample(emp);
	while(resultado.hasNext()){
           Empresa empl = (Empresa) resultado.next();
           this.jCEmpresas.addItem(empl.getNombre());
	}
    }
    
    private void fillCarreras(){
        this.carreras.forEach((carrera) -> this.jCCarrera.addItem(carrera));
    }
    
    private Empresa buscarObjetoEmpresa(String nombre_empresa){
        try{
            Empresa em = null;
            ObjectSet resultado = this.dbempresa.queryByExample(em);
            while(resultado.hasNext()){
               em = (Empresa) resultado.next();
               if(em.getNombre().equals(nombre_empresa)){
                   return em ;
               }
            }
            return null;
        }
        catch(DatabaseClosedException | Db4oIOException e){
            System.out.println(e.getMessage());
            return null;
        }
    }
    
    private void limpiarJText(){
        this.jTNombre.setText("");
        this.jTApellidos.setText("");
        this.jTMatricula.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jLStatus = new javax.swing.JLabel();
        jCEmpresas = new javax.swing.JComboBox<>();
        jCEspecialidades = new javax.swing.JComboBox<>();
        jCCarrera = new javax.swing.JComboBox<>();
        jTMatricula = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 49, 67));

        jPanel2.setBackground(new java.awt.Color(239, 240, 242));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Vinculación de alumnos");

        jBRegresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menor-que-48.png"))); // NOI18N
        jBRegresar.setBorder(null);
        jBRegresar.setBorderPainted(false);
        jBRegresar.setContentAreaFilled(false);
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });

        jLStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBRegresar)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jCEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEmpresasActionPerformed(evt);
            }
        });

        jCEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEspecialidadesActionPerformed(evt);
            }
        });

        jCCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCarreraActionPerformed(evt);
            }
        });

        jTMatricula.setBackground(new java.awt.Color(239, 240, 242));
        jTMatricula.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTMatricula.setBorder(null);
        jTMatricula.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jTApellidos.setBackground(new java.awt.Color(239, 240, 242));
        jTApellidos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTApellidos.setBorder(null);
        jTApellidos.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jTNombre.setBackground(new java.awt.Color(239, 240, 242));
        jTNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTNombre.setBorder(null);
        jTNombre.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jBguardar.setBackground(new java.awt.Color(239, 240, 242));
        jBguardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBguardar.setText("Guardar datos del alumno");
        jBguardar.setBorder(null);
        jBguardar.setBorderPainted(false);
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 240, 242));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 240, 242));
        jLabel3.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(239, 240, 242));
        jLabel5.setText("Carrera:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(239, 240, 242));
        jLabel6.setText("Especialidad:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(239, 240, 242));
        jLabel7.setText("Empresas:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(239, 240, 242));
        jLabel4.setText("Matrícula:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTNombre)
                    .addComponent(jTApellidos)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCCarrera, 0, 276, Short.MAX_VALUE)
                    .addComponent(jCEspecialidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCEmpresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCarreraActionPerformed
       String carrera = (String) this.jCCarrera.getSelectedItem();
       if(carrera.equals("TIC")){
           this.especialidadestic.forEach((especialidad) -> this.jCEspecialidades.addItem(especialidad));
       }
       else{
           this.jCEspecialidades.removeAllItems();
       }
    }//GEN-LAST:event_jCCarreraActionPerformed

    private void jCEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEmpresasActionPerformed
        
    }//GEN-LAST:event_jCEmpresasActionPerformed

    private void jCEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEspecialidadesActionPerformed
        
    }//GEN-LAST:event_jCEspecialidadesActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        String nombre = this.jTNombre.getText();
        String apellidos = this.jTApellidos.getText();
        String matricula = this.jTMatricula.getText();
        String carrera = (String) this.jCCarrera.getSelectedItem();
        String especialidad = (String) this.jCEspecialidades.getSelectedItem();
        String nombre_empresa = (String) this.jCEmpresas.getSelectedItem();
        Empresa empresa = this.buscarObjetoEmpresa(nombre_empresa);
        
        if(!matricula.isEmpty() && !nombre.isEmpty() && !apellidos.isEmpty() && !carrera.isEmpty() && !empresa.getNombre().isEmpty()){
            Alumno al = new Alumno(nombre,
                apellidos,
                carrera,
                especialidad,
                matricula,
                empresa);
            this.dbalumno.store(al);
            this.limpiarJText();
            this.jLStatus.setForeground(Color.BLUE);
            this.jLStatus.setText("Alumno ingresado correctamente");
        }
        else{
            this.jLStatus.setForeground(Color.RED);
            this.jLStatus.setText("El alumno no se ha ingresado correctamente");
        }
        
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        this.setVisible(false);
        this.menu.setVisible(true);
    }//GEN-LAST:event_jBRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRegresar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox<String> jCCarrera;
    private javax.swing.JComboBox<String> jCEmpresas;
    private javax.swing.JComboBox<String> jCEspecialidades;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTMatricula;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
